language: node_js
node_js: lts/*
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH=$HOME/.yarn/bin:$PATH
env:
  global:
  - REACT_APP_API_KEY=$FIREBASE_API_KEY
  - REACT_APP_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
  - REACT_APP_DATABASE_URL=$FIREBASE_DATABASE_URL
  - REACT_APP_PROJECT_ID=$FIREBASE_PROJECT_ID
  - REACT_APP_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
  - REACT_APP_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
cache:
  yarn: true
install:
- yarn
script:
- yarn build
- yarn test -- --coverage
after_script:
- COVERALLS_REPO_TOKEN=$COVERALLS_TOKEN yarn coveralls
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT_ID
after_deploy:
  message: 'Deploy Success'

